name: GateKeeper Policy

on:
  push:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #TF_ACTION_WORKING_DIR: 'gatekeeper'
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    name: Deploy Gatekeeper
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
      - name: Config Kubectl
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      - name: Login to EKS
        run: |
          aws eks update-kubeconfig --name gitaction
      - name: fetch gatekeeper image
        run: |
          kubectl apply -f https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.8/deploy/gatekeeper.yaml
      - name: check pods
        run: |
          kubectl get pods -n gatekeeper-system
      - name: check logs
        run: |
          kubectl logs -l control-plane=audit-controller -n gatekeeper-system
          kubectl logs -l control-plane=controller-manager -n gatekeeper-system